- name: Install Erlang Package
  yum:
    url: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: present

- name: Add Yum repository
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ Server
  yum:
    name: rabbitmq-server
    state: present

- name: Start RabbitMQ server
 systemd:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Create RabbitMQ User
  community.rabbitmq.rabbitmq_user:
     user: roboshop
     password: roboshop
     vhost: /
     configure_priv: .*
     read_priv: .*
     write_priv: .*
     state: present
     tags: administrator