- name: create an user by accepting the password from user
  vars_prompt:
    - name: password
      prompt: Provide a simple password for provisioning of users

  tasks:
    - name: Print the password
    debug:
      msg: Password is {{password}}



